[package]
name = "example01"
version = "0.1.0"
authors = ["Behxhet Sadiku <bensadiku65@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heroku_rs = { path = "../", default-features = true }
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"